kind: Service
apiVersion: v1
metadata:
  name: service-services
  annotations:
    cloud.google.com/backend-config: '{"default": "services-config"}'
spec:
  type: NodePort
  selector:
    app: services
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31025