name: Unit tests
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  test_services:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -t services-image .
      - name: Test
        run: docker run --rm --network="host" -e TEST=true -e DB_HOST='localhost' -e DB_PORT='5432' -e DB_PASSWORD='postgres' -e DB_USER='postgres' -e DB_NAME='postgres' services-image
